import { Landing } from '@/components/Landing/Landing'
import useAuthToken from '@/hooks/useAuthToken'
import Head from 'next/head'

export default function Home() {
  const { authToken } = useAuthToken()

  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {authToken && <Landing />}
    </>
  )
}
